version: 0.2

phases: 
    install:
        commands:
            - apt-get update && apt-get install -y gnupg software-properties-common curl
            - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
            - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            - apt-get update && sudo apt-get install terraform
        
        
    build:
        commands: 
            - terraform init
            - terraform plan
            - terraform apply
            - echo "yes"
