
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update && apt-get install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install terraform
      
  build:
    commands:
    
      - terraform --version
      - terraform init -input=false
      - terraform plan -var-file="secret.tfvars"
      - terraform apply -var-file="secret.tfvars"
      - echo "yes"
      

